Repository goorm-petmates/petmates_backend, pull requests merged in 2024-03, with the labels that each got.

#43 feat(#33): 예약 요청 확인 #33
  src/main/java/kr/co/petmates/api/bussiness/reserve/controller/BookingController.java
  src/main/java/kr/co/petmates/api/bussiness/reserve/dto/ResponseFailedDto.java
  src/main/java/kr/co/petmates/api/bussiness/reserve/entity/Booking.java
  src/main/java/kr/co/petmates/api/bussiness/reserve/service/BookingService.java
  src/main/java/kr/co/petmates/api/config/jwt/JwtSecurityConfig.java
  src/main/java/kr/co/petmates/api/config/jwt/JwtUtil.java
Labels: enhancement, 우선순위: 상

#45 feat(#44): 예약 확정 후 취소
  src/main/java/kr/co/petmates/api/bussiness/reserve/controller/BookingController.java
  src/main/java/kr/co/petmates/api/bussiness/reserve/dto/RequestCancelBookingDto.java
  src/main/java/kr/co/petmates/api/bussiness/reserve/dto/ResponseCancelBookingDto.java
  src/main/java/kr/co/petmates/api/bussiness/reserve/repository/CanceledBookingRepository.java
  src/main/java/kr/co/petmates/api/bussiness/reserve/service/BookingService.java
  src/main/resources/application.yml
Labels: enhancement, 우선순위: 상

#48 Feat/29 kakao jwt token
  package-lock.json
  src/main/java/kr/co/petmates/api/bussiness/members/controller/MembersController.java
  src/main/java/kr/co/petmates/api/bussiness/oauth/controller/KakaoOauthController.java
  src/main/java/kr/co/petmates/api/bussiness/oauth/service/JwtTokenCheckService.java
  src/main/java/kr/co/petmates/api/bussiness/oauth/service/JwtTokenSaveService.java
  src/main/java/kr/co/petmates/api/bussiness/oauth/service/UserService.java
  src/main/java/kr/co/petmates/api/bussiness/pet/controller/PetInfoCheckController.java
  src/main/java/kr/co/petmates/api/bussiness/pet/dto/PetCheckDto.java
  src/main/java/kr/co/petmates/api/bussiness/pet/service/PetService.java
  src/main/java/kr/co/petmates/api/bussiness/reserve/controller/BookingRequestController.java
  src/main/java/kr/co/petmates/api/bussiness/reserve/dto/BookingRequestDto.java
  src/main/java/kr/co/petmates/api/bussiness/reserve/dto/BookingResponseDto.java
  src/main/java/kr/co/petmates/api/bussiness/reserve/service/BookingRequestService.java
  src/main/java/kr/co/petmates/api/bussiness/review/controller/ReviewController.java
  src/main/java/kr/co/petmates/api/config/security/SecurityConfig.java
  src/main/resources/application.yml
Labels: enhancement

#51 fix(#50) Pet엔티티의 성별 타입 변경
  src/main/java/kr/co/petmates/api/bussiness/pet/dto/PetDto.java
  src/main/java/kr/co/petmates/api/bussiness/pet/entity/Pet.java
  src/main/java/kr/co/petmates/api/config/security/SecurityConfig.java
Labels: bug, 우선순위: 상

#52 feat(#47): 반려인의 반려동물 정보 목록
  src/main/java/kr/co/petmates/api/bussiness/pet/controller/PetController.java
  src/main/java/kr/co/petmates/api/bussiness/pet/dto/PetResponseDto.java
  src/main/java/kr/co/petmates/api/bussiness/pet/entity/Pet.java
  src/main/java/kr/co/petmates/api/bussiness/pet/repository/PetRepository.java
  src/main/java/kr/co/petmates/api/bussiness/pet/service/PetService.java
Labels: enhancement, 우선순위: 상
